apiVersion: v1
kind: ConfigMap
metadata:
  name: market-service-local
  namespace: b2c
data:
  config.conf: |-
    include "beta.conf"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-service-pars
  namespace: b2c
data:
  config.conf: |-
    include "prod.conf"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-service-shatel
  namespace: b2c
data:
  config.conf: |-
    include "prod.conf"

---
kind: Service
apiVersion: v1
metadata:
  name: market-service
  namespace: b2c
spec:
  selector:
    app: market-service
  ports:
  - name: market-service
    protocol: TCP
    port: 9000

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: market-service
  namespace: b2c
spec:
  replicas: $REPLICAS
  template:
    metadata:
      labels:
        app: market-service
    spec:
      imagePullSecrets:
      - name: $imagePullSecrets
      containers:
      - name: market-service
        imagePullPolicy: "Always"
        image: $IMAGE_TAG
        command: ["market-service-1.0/bin/market-service"]
        args: [
          "-J-Xms256m",
          "-J-Xmx512m",
          "-J-server",
          "-Dplay.http.secret.key=abcdefghijk",
          "-Dhttp.port=9000",
          "-Dconfig.file=/pintapin/config/config.conf",
          "-Dpidfile.path=/dev/null"
        ]
        ports:
        - name: app
          containerPort: 9000
        volumeMounts:
        - name: nfs
          mountPath: "/pintapin/share"
        - name: config
          mountPath: "/pintapin/config"
        livenessProbe:
          httpGet:
            path: /health
            port: app
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: app
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
      volumes:
      - name: config
        configMap:
          name: "market-service-$CONTEXT"
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: market-service
  namespace: b2c
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/rewrite-target: /${DOLLAR}1 
    kubernetes.io/ingress.class: "$CI_PROJECT_NAMESPACE-$CONTEXT"
spec:
  rules:
  - host: snapptrip.com
    http:
      paths:
      - path: "/service2/market/?(.*)"
        backend:
          serviceName: market-service
          servicePort: 9000

