replicas: 1
namespace: b2c
context: local
imagePullSecrets: regsecret
image: git.pinsvc.net:4567/b2c/market-service/beta
baseConfig: beta
ingressClass: b2c-local

extraConfig: ""

service:
  type: ClusterIP
  port: 9000
resources: {}
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

ingress:
  enabled: true
  path: "/service2/market/?(.*)"
  hosts:
    - b2c.ptp
    - www.snapptrip.com
  tls:
    - secretName: www-pintapin-com-ssl
      hosts:
        - www.pintapin.com
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'false'
    nginx.ingress.kubernetes.io/cors-allow-headers: >-
      DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,channel,search-session,token
    nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS, DELETE'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'