replicas: 1
namespace: b2c 
context: local
imagePullSecrets: regsecret
image: git.pinsvc.net:4567/b2c/market-service/beta
baseConfig: beta
ingressClass: b2c-local
extraConfig: ""

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  path: /service2/market/?(.*)
  hosts:
    - b2c.ptp
    - www.snapptrip.com
  tls:
    - secretName: www-pintapin-com-ssl
      hosts:
        - www.pintapin.com
    - secretName: snapptrip-com-ssl
      hosts:
        - www.snapptrip.com
        - hotelview.snapptrip.com
  annotations: 
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Language fa;
        rewrite ^/(.+)\[.+\](.+)$ $1$2 permanent;  # https://pintapin.atlassian.net/browse/SOF-624    
        rewrite ^/hotels$ / permanent;
        #if ($request_uri ~* ^/(.+?)\;) {
        #    set $args '';
        #    rewrite ^(.*)\;$ $1 permanent;
        #}    

        location ^~ /service2/market {
            proxy_pass_header Server;
            proxy_pass_header X-Referer;
            proxy_pass_header lang;
            proxy_redirect off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Referer $http_referer;
            proxy_set_header X-Scheme $scheme;
            #rewrite /service2/auth(.*) /$1  break;
            proxy_pass http://ingress-nginx.core:80;
        }
     
